### ISSUE TITLE
Grayscale Prototype

### ISSUE THREAD

**Issue by RavinAnderson** [dartmouth-cs98-23f/arena#32]
https://www.figma.com/file/GpweAcu2tVdE31yNRqhpKo/Prototype%3A-Ravin%2C-Itish%2C-Jeff%2C-Qaisar%2C-Ian%2C-Mahir?type=design&node-id=0%3A1&mode=design&t=kAYTLoHcfBcgyfXY-1

**Comment by nataliesvoboda** [comment]
👍 solid start - a few more details to work out (I left figma comments)
